language: go
go:
  - 1.8.x
install:
  - go get github.com/Masterminds/glide
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - glide install
before_script:
  - go build ./cmd/semantic-release/
script:
  - go test -v $(glide novendor)
after_success:
  - ./release
notifications:
  email: false
