language: go
go:
  - 1.9.x
install:
  - nvm install 7
  - node -v && npm -v
  - go get github.com/Masterminds/glide
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - glide install
before_script:
  - go build ./cmd/semantic-release/
after_success:
  - ./release
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
