#!/bin/bash

set -xeuo pipefail

rm -rvf ./bin

if [ ! -f .version ]; then
	echo "Must have .version file for build" 1>&2
	exit 1
fi
VERSION=$(cat .version)

pids=()
for os in darwin linux ; do
	for arch in arm64 amd64 ; do
		CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -o bin/semantic-release_v${VERSION}_${os}_${arch} -ldflags="-s -w -X main.SRVERSION=$VERSION" ./cmd/semantic-release/ &
		pids+=($!)
	done
done
wait
exit $?
