#!/usr/bin/env bash

set -xeuo pipefail

if [ ! -f .version ]; then
	echo "Must have .version file for build" 1>&2
	exit 1
fi
if [ ! -d bin ]; then
	echo "Must build first" 1>&2
	exit 1
fi
if [ -z "${GITHUB_TOKEN:-}" ]; then
	read -s -p 'GitHub Token (silent)> ' GITHUB_TOKEN
fi

# only set the token for invoking `ghr`, don't use it for push as it
# probably doesn't have permissions

GITHUB_TOKEN= git push
# only push the tag we are releasing
GITHUB_TOKEN= git push origin v$(cat .version)

GITHUB_TOKEN="$GITHUB_TOKEN" ghr -u 6RiverSystems -r go-semantic-release v$(cat .version) ./bin/
