#!/usr/bin/env bash

set -xeuo pipefail

# use the app to release itself
go run ./cmd/semantic-release/main.go -nochange -flow -noci -vf -update ./npm-package/package.json -slug 6RiverSystems/go-semantic-release
